In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = sns.load_dataset('car_crashes')
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [7]:
df.sum()

total                                                         805.3
speeding                                                    254.908
alcohol                                                     249.226
not_distracted                                              692.232
no_previous                                                 714.249
ins_premium                                                45234.84
ins_losses                                                  6859.15
abbrev            ALAKAZARCACOCTDEDCFLGAHIIDILINIAKSKYLAMEMDMAMI...
dtype: object

In [9]:
df.sum(axis=1, numeric_only=True)

0      994.490
1     1250.760
2     1073.618
3     1044.322
4     1085.200
5     1021.514
6     1273.658
7     1346.698
8     1431.239
9     1364.454
10    1107.742
11    1045.800
12     777.954
13     988.340
14     869.260
15     814.712
16     969.964
17    1072.984
18    1545.825
19     809.639
20    1283.480
21    1173.420
22    1308.554
23     942.018
24    1096.896
25     991.603
26     976.688
27     896.419
28    1221.941
29     905.610
30    1495.866
31    1047.824
32    1424.787
33     894.020
34     882.120
35     879.613
36    1129.423
37     949.768
38    1126.280
39    1335.643
40    1060.344
41     833.692
42     984.515
43    1230.644
44     957.619
45     873.546
46     963.437
47    1038.008
48    1227.518
49     817.226
50     973.210
dtype: float64

In [10]:
df.median(numeric_only=True)

total              15.600
speeding            4.608
alcohol             4.554
not_distracted     13.857
no_previous        13.775
ins_premium       858.970
ins_losses        136.050
dtype: float64

In [11]:
df.mean(numeric_only=True)

total              15.790196
speeding            4.998196
alcohol             4.886784
not_distracted     13.573176
no_previous        14.004882
ins_premium       886.957647
ins_losses        134.493137
dtype: float64

In [12]:
df.max()

total                23.9
speeding             9.45
alcohol            10.038
not_distracted     23.661
no_previous         21.28
ins_premium       1301.52
ins_losses         194.78
abbrev                 WY
dtype: object

In [13]:
df.min()

total                5.9
speeding           1.792
alcohol            1.593
not_distracted      1.76
no_previous          5.9
ins_premium       641.96
ins_losses         82.75
abbrev                AK
dtype: object

In [14]:
alcohal = df['alcohol']
alcohal.idxmax()

34

In [15]:
df.std(numeric_only=True)

total               4.122002
speeding            2.017747
alcohol             1.729133
not_distracted      4.508977
no_previous         3.764672
ins_premium       178.296285
ins_losses         24.835922
dtype: float64

In [16]:
df.var(numeric_only=True)

total                16.990902
speeding              4.071303
alcohol               2.989901
not_distracted       20.330874
no_previous          14.172755
ins_premium       31789.565170
ins_losses          616.823046
dtype: float64

In [19]:
df['alcohol'].std()

1.7291329077167608

In [20]:
df['abbrev'].value_counts()

abbrev
AL    1
PA    1
NV    1
NH    1
NJ    1
NM    1
NY    1
NC    1
ND    1
OH    1
OK    1
OR    1
RI    1
MT    1
SC    1
SD    1
TN    1
TX    1
UT    1
VT    1
VA    1
WA    1
WV    1
WI    1
NE    1
MO    1
AK    1
ID    1
AZ    1
AR    1
CA    1
CO    1
CT    1
DE    1
DC    1
FL    1
GA    1
HI    1
IL    1
MS    1
IN    1
IA    1
KS    1
KY    1
LA    1
ME    1
MD    1
MA    1
MI    1
MN    1
WY    1
Name: count, dtype: int64

In [21]:
total = df.total
total.value_counts()

total
14.1    2
12.8    2
13.6    2
21.4    2
19.4    2
23.9    2
14.9    1
14.7    1
11.6    1
11.2    1
18.4    1
12.3    1
16.8    1
19.9    1
17.6    1
18.2    1
11.1    1
19.5    1
11.3    1
12.7    1
10.6    1
23.8    1
13.8    1
16.1    1
18.8    1
9.6     1
18.1    1
18.6    1
22.4    1
12.0    1
10.8    1
16.2    1
5.9     1
17.9    1
15.6    1
17.5    1
15.3    1
14.5    1
15.7    1
17.8    1
20.5    1
15.1    1
12.5    1
8.2     1
17.4    1
Name: count, dtype: int64

In [22]:
df.describe()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,15.790196,4.998196,4.886784,13.573176,14.004882,886.957647,134.493137
std,4.122002,2.017747,1.729133,4.508977,3.764672,178.296285,24.835922
min,5.900000,1.792000,1.593000,1.760000,5.900000,641.960000,82.750000
25%,12.750000,3.766500,3.894000,10.478000,11.348000,768.430000,114.645000
50%,15.600000,4.608000,4.554000,13.857000,13.775000,858.970000,136.050000
75%,18.500000,6.439000,5.604000,16.140000,16.755000,1007.945000,151.870000
max,23.900000,9.450000,10.038000,23.661000,21.280000,1301.520000,194.780000